name: Build
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: packages/screens

      - name: Clone unconscious
        run: git clone https://github.com/roj234/unconscious.git packages/unconscious

      - name: Setup monorepo root
        run: |
          echo '{ "private": true, "workspaces": ["packages/*"] }' > package.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        working-directory: packages/screens

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: packages/screens/dist